name: PR Test Builds

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        path: "app/build/outputs/apk/debug/app-debug.apk"

    - name: Upload APK to Discord
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
        username: animebinge Test Builds
        avatar-url: "https://media.discordapp.net/attachments/927944825016311858/1046676593252253726/animebinge.png"
        content: "Latest Beta APK"
        filename: app/build/outputs/apk/debug/app-debug.apk
